/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.38
 * Generated at: 2025-07-25 10:51:51 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class AddPrice_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/rajen/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1308849601000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\" crossorigin=\"anonymous\">\r\n");
      out.write("    <script src=\"https://unpkg.com/axios/dist/axios.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <header class=\"bg-dark text-white py-3\">\r\n");
      out.write("        <div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("            <!-- Logo -->\r\n");
      out.write("            <img src=\"https://www.x-workz.in/Logo.png\" alt=\"Coders World Logo\" style=\"max-height: 50px;\">\r\n");
      out.write("            <!-- Heading -->\r\n");
      out.write("            <nav class=\"d-flex justify-content-center\">\r\n");
      out.write("            <a href=\"addLocations?email=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"btn btn-dark btn-sm mx-2 \">Locations</a>\r\n");
      out.write("            <a href=\"addTimings?email=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"btn btn-dark btn-sm mx-2\">Timings</a>\r\n");
      out.write("            <a href=\"addTrainType?email=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"btn btn-dark btn-sm mx-2\">Add Train</a>\r\n");
      out.write("             <a href=\"addPriceList?email=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"btn btn-dark btn-sm mx-2\">Price</a>\r\n");
      out.write("             <a href=\"readTrain?email=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"btn btn-dark btn-sm mx-2\">View Data</a>\r\n");
      out.write("            </nav>\r\n");
      out.write("            <h1 class=\"text-center mb-0 flex-grow-1\"></h1>\r\n");
      out.write("                        <div class=\"dropdown\">\r\n");
      out.write("                   <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/getImage/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.imageName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"rounded-circle\" alt=\"img\" width=90/>\r\n");
      out.write("\r\n");
      out.write("                            <a class=\"btn btn-sm btn-secondary dropdown-toggle dropdown-toggle-split mx-3\" href=\"\" role=\"button\" id=\"dropdownMenuLink\" data-bs-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                   ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.userName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("                            </a>\r\n");
      out.write("                            <div class=\"dropdown-menu\" aria-labelledby=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.userName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("                                <a class=\"dropdown-item\" href=\"UpdateProfile?email=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Profile</a>\r\n");
      out.write("                                <a class=\"dropdown-item\" href=\"MetroLogin\">Log out</a>\r\n");
      out.write("                                <a class=\"dropdown-item\" href=\"index.jsp\">Home</a>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("<br>\r\n");
      out.write("    <div class=\"card mx-auto\" style=\"max-width: 800;border-radius: 15px; overflow: hidden;\">\r\n");
      out.write("        <div class=\"card-body\"   style=\"background-color: black;\">\r\n");
      out.write("    <div style=\"max-width: 500px; margin: auto;\">\r\n");
      out.write("        <div class=\"mb-3\">\r\n");
      out.write("            <h5 class=\"mb-0\"></h5>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"card-auto\">\r\n");
      out.write("            <div class=\"card-body\"  >\r\n");
      out.write("            <form action=\"price\" method=\"post\">\r\n");
      out.write("       <div class=\"col-md-6 mb-1\">\r\n");
      out.write("                                   <div>\r\n");
      out.write("                                   <h5 class=\"text-right\"   style=\"color:white\">ADD PRICE :</h5>\r\n");
      out.write("                                   </div>\r\n");
      out.write("                                   </div>\r\n");
      out.write("                           <label for=\"email\" class=\"form-label\" hidden>email</label>\r\n");
      out.write("                         <input type=\"text\"  name=\"email\" id=\"trainNumber\" class=\"form-control\" placeholder=\"Enter the email\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" hidden>\r\n");
      out.write("                          </div>\r\n");
      out.write("                          <div class=\"mb-3\">\r\n");
      out.write("                              <label for=\"source\"   style=\"color:white\" class=\"form-label\">Select Source Station</label>\r\n");
      out.write("                              <select name=\"source\" id=\"sourceId\" class=\"form-control\" required>\r\n");
      out.write("                                  <option value=\"\">Select Source Station</option>\r\n");
      out.write("                                  <!-- Purple Line Stations -->\r\n");
      out.write("                                  <optgroup label=\"Purple Line\">\r\n");
      out.write("                                      <option value=\"Baiyappanahalli\">Baiyappanahalli</option>\r\n");
      out.write("                                      <option value=\"Indiranagar\">Indiranagar</option>\r\n");
      out.write("                                      <option value=\"Halasuru\">Halasuru</option>\r\n");
      out.write("                                      <option value=\"Trinity\">Trinity</option>\r\n");
      out.write("                                      <option value=\"MG Road\">M.G. Road</option>\r\n");
      out.write("                                      <option value=\"Cunningham Road\">Cunningham Road</option>\r\n");
      out.write("                                      <option value=\"Shanthinagar\">Shanthinagar</option>\r\n");
      out.write("                                      <option value=\"Lalbagh\">Lalbagh</option>\r\n");
      out.write("                                      <option value=\"South End Circle\">South End Circle</option>\r\n");
      out.write("                                      <option value=\"Jayanagar\">Jayanagar</option>\r\n");
      out.write("                                      <option value=\"RV Road\">Rashtreeya Vidyalaya Road (RV Road)</option>\r\n");
      out.write("                                      <option value=\"Banashankari\">Banashankari</option>\r\n");
      out.write("                                      <option value=\"Yelachenahalli\">Yelachenahalli</option>\r\n");
      out.write("                                      <option value=\"Silk Board\">Silk Board</option>\r\n");
      out.write("                                      <option value=\"BTM Layout\">BTM Layout</option>\r\n");
      out.write("                                      <option value=\"JP Nagar\">J.P. Nagar</option>\r\n");
      out.write("                                      <option value=\"Kengeri\">Kengeri</option>\r\n");
      out.write("                                  </optgroup>\r\n");
      out.write("                                  <!-- Green Line Stations -->\r\n");
      out.write("                                  <optgroup label=\"Green Line\">\r\n");
      out.write("                                      <option value=\"Nagasandra\">Nagasandra</option>\r\n");
      out.write("                                      <option value=\"Dasarahalli\">Dasarahalli</option>\r\n");
      out.write("                                      <option value=\"Jalahalli\">Jalahalli</option>\r\n");
      out.write("                                      <option value=\"Peenya Industry\">Peenya Industry</option>\r\n");
      out.write("                                      <option value=\"Peenya\">Peenya</option>\r\n");
      out.write("                                      <option value=\"Goraguntepalya\">Goraguntepalya</option>\r\n");
      out.write("                                      <option value=\"Yeshwanthpur\">Yeshwanthpur</option>\r\n");
      out.write("                                      <option value=\"Sandal Soap Factory\">Sandal Soap Factory</option>\r\n");
      out.write("                                      <option value=\"Mahalakshmi\">Mahalakshmi</option>\r\n");
      out.write("                                      <option value=\"Rajajinagar\">Rajajinagar</option>\r\n");
      out.write("                                      <option value=\"Kuvempu Road\">Kuvempu Road</option>\r\n");
      out.write("                                      <option value=\"Srirampura\">Srirampura</option>\r\n");
      out.write("                                      <option value=\"Mantri Square Sampige Road\">Mantri Square Sampige Road</option>\r\n");
      out.write("                                      <option value=\"Krantivira Sangolli Rayanna\">Krantivira Sangolli Rayanna (Majestic)</option>\r\n");
      out.write("                                      <option value=\"Chickpete\">Chickpete</option>\r\n");
      out.write("                                      <option value=\"Krishna Rajendra Market\">Krishna Rajendra Market</option>\r\n");
      out.write("                                      <option value=\"National College\">National College</option>\r\n");
      out.write("                                      <option value=\"Lalbagh\">Lalbagh</option>\r\n");
      out.write("                                      <option value=\"South End Circle\">South End Circle</option>\r\n");
      out.write("                                      <option value=\"Jayanagar\">Jayanagar</option>\r\n");
      out.write("                                      <option value=\"Rashtreeya Vidyalaya Road\">Rashtreeya Vidyalaya Road</option>\r\n");
      out.write("                                      <option value=\"Banashankari\">Banashankari</option>\r\n");
      out.write("                                      <option value=\"Jaya Prakash Nagar\">Jaya Prakash Nagar</option>\r\n");
      out.write("                                      <option value=\"Yelachenahalli\">Yelachenahalli</option>\r\n");
      out.write("                                      <option value=\"Anjanapura\">Anjanapura</option>\r\n");
      out.write("                                  </optgroup>\r\n");
      out.write("                              </select>\r\n");
      out.write("                          </div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"mb-3\">\r\n");
      out.write("    <label for=\"destination\"   style=\"color:white\"class=\"form-label\">Select Destination Station</label>\r\n");
      out.write("    <select name=\"destination\" onBlur=\"destination()\" id=\"destinationId\" class=\"form-control\" required>\r\n");
      out.write("        <option value=\"\">Select Destination Station</option>\r\n");
      out.write("        <!-- Purple Line Stations -->\r\n");
      out.write("        <optgroup label=\"Purple Line\">\r\n");
      out.write("            <option value=\"Baiyappanahalli\">Baiyappanahalli</option>\r\n");
      out.write("            <option value=\"Indiranagar\">Indiranagar</option>\r\n");
      out.write("            <option value=\"Halasuru\">Halasuru</option>\r\n");
      out.write("            <option value=\"Trinity\">Trinity</option>\r\n");
      out.write("            <option value=\"MG Road\">M.G. Road</option>\r\n");
      out.write("            <option value=\"Cunningham Road\">Cunningham Road</option>\r\n");
      out.write("            <option value=\"Shanthinagar\">Shanthinagar</option>\r\n");
      out.write("            <option value=\"Lalbagh\">Lalbagh</option>\r\n");
      out.write("            <option value=\"South End Circle\">South End Circle</option>\r\n");
      out.write("            <option value=\"Jayanagar\">Jayanagar</option>\r\n");
      out.write("            <option value=\"RV Road\">Rashtreeya Vidyalaya Road (RV Road)</option>\r\n");
      out.write("            <option value=\"Banashankari\">Banashankari</option>\r\n");
      out.write("            <option value=\"Yelachenahalli\">Yelachenahalli</option>\r\n");
      out.write("            <option value=\"Silk Board\">Silk Board</option>\r\n");
      out.write("            <option value=\"BTM Layout\">BTM Layout</option>\r\n");
      out.write("            <option value=\"JP Nagar\">J.P. Nagar</option>\r\n");
      out.write("            <option value=\"Kengeri\">Kengeri</option>\r\n");
      out.write("        </optgroup>\r\n");
      out.write("        <!-- Green Line Stations -->\r\n");
      out.write("        <optgroup label=\"Green Line\">\r\n");
      out.write("            <option value=\"Nagasandra\">Nagasandra</option>\r\n");
      out.write("            <option value=\"Dasarahalli\">Dasarahalli</option>\r\n");
      out.write("            <option value=\"Jalahalli\">Jalahalli</option>\r\n");
      out.write("            <option value=\"Peenya Industry\">Peenya Industry</option>\r\n");
      out.write("            <option value=\"Peenya\">Peenya</option>\r\n");
      out.write("            <option value=\"Goraguntepalya\">Goraguntepalya</option>\r\n");
      out.write("            <option value=\"Yeshwanthpur\">Yeshwanthpur</option>\r\n");
      out.write("            <option value=\"Sandal Soap Factory\">Sandal Soap Factory</option>\r\n");
      out.write("            <option value=\"Mahalakshmi\">Mahalakshmi</option>\r\n");
      out.write("            <option value=\"Rajajinagar\">Rajajinagar</option>\r\n");
      out.write("            <option value=\"Kuvempu Road\">Kuvempu Road</option>\r\n");
      out.write("            <option value=\"Srirampura\">Srirampura</option>\r\n");
      out.write("            <option value=\"Mantri Square Sampige Road\">Mantri Square Sampige Road</option>\r\n");
      out.write("            <option value=\"Krantivira Sangolli Rayanna\">Krantivira Sangolli Rayanna (Majestic)</option>\r\n");
      out.write("            <option value=\"Chickpete\">Chickpete</option>\r\n");
      out.write("            <option value=\"Krishna Rajendra Market\">Krishna Rajendra Market</option>\r\n");
      out.write("            <option value=\"National College\">National College</option>\r\n");
      out.write("            <option value=\"Lalbagh\">Lalbagh</option>\r\n");
      out.write("            <option value=\"South End Circle\">South End Circle</option>\r\n");
      out.write("            <option value=\"Jayanagar\">Jayanagar</option>\r\n");
      out.write("            <option value=\"Rashtreeya Vidyalaya Road\">Rashtreeya Vidyalaya Road</option>\r\n");
      out.write("            <option value=\"Banashankari\">Banashankari</option>\r\n");
      out.write("            <option value=\"Jaya Prakash Nagar\">Jaya Prakash Nagar</option>\r\n");
      out.write("            <option value=\"Yelachenahalli\">Yelachenahalli</option>\r\n");
      out.write("            <option value=\"Anjanapura\">Anjanapura</option>\r\n");
      out.write("        </optgroup>\r\n");
      out.write("    </select>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("                <label for=\"addTrainType\"   style=\"color:white\" class=\"form-label\">Add Train Type</label>\r\n");
      out.write("                <select name=\"trainType\" id=\"trainType\" class=\"form-control\" required>\r\n");
      out.write("                    <option value=\"\">Select Train Type</option>\r\n");
      out.write("                    <option value=\"Purple\">Purple</option>\r\n");
      out.write("                    <option value=\"Green\">Green</option>\r\n");
      out.write("                </select>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("                           <div class=\"mb-3\">\r\n");
      out.write("                        <label for=\"distance\"   style=\"color:white\" class=\"form-label\">distance*</label>\r\n");
      out.write("                         <input type=\"text\"  name=\"distance\" id=\"distance\" class=\"form-control \" placeholder=\"Enter the distance\">\r\n");
      out.write("                         </div>\r\n");
      out.write("\r\n");
      out.write("                         <div class=\"mb-3\">\r\n");
      out.write("                             <label for=\"station\"  style=\"color:white\"  class=\"form-label\">Select Station</label>\r\n");
      out.write("                             <select name=\"station\" id=\"station\" class=\"form-control\" required>\r\n");
      out.write("                                 <option value=\"\">Select Station</option>\r\n");
      out.write("                                 <!-- Purple Line Stations -->\r\n");
      out.write("                                 <option value=\"Baiyappanahalli\">Baiyappanahalli</option>\r\n");
      out.write("                                 <option value=\"Indiranagar\">Indiranagar</option>\r\n");
      out.write("                                 <option value=\"Halasuru\">Halasuru</option>\r\n");
      out.write("                                 <option value=\"Trinity\">Trinity</option>\r\n");
      out.write("                                 <option value=\"MG Road\">M.G. Road</option>\r\n");
      out.write("                                 <option value=\"Cunningham Road\">Cunningham Road</option>\r\n");
      out.write("                                 <option value=\"Shanthinagar\">Shanthinagar</option>\r\n");
      out.write("                                 <option value=\"Lalbagh\">Lalbagh</option>\r\n");
      out.write("                                 <option value=\"South End Circle\">South End Circle</option>\r\n");
      out.write("                                 <option value=\"Jayanagar\">Jayanagar</option>\r\n");
      out.write("                                 <option value=\"RV Road\">Rashtreeya Vidyalaya Road (RV Road)</option>\r\n");
      out.write("                                 <option value=\"Banashankari\">Banashankari</option>\r\n");
      out.write("                                 <option value=\"Yelachenahalli\">Yelachenahalli</option>\r\n");
      out.write("                                 <option value=\"Silk Board\">Silk Board</option>\r\n");
      out.write("                                 <option value=\"BTM Layout\">BTM Layout</option>\r\n");
      out.write("                                 <option value=\"JP Nagar\">J.P. Nagar</option>\r\n");
      out.write("                                 <option value=\"Kengeri\">Kengeri</option>\r\n");
      out.write("                                 <!-- Green Line Stations -->\r\n");
      out.write("                                 <option value=\"Nagasandra\">Nagasandra</option>\r\n");
      out.write("                                 <option value=\"Dasarahalli\">Dasarahalli</option>\r\n");
      out.write("                                 <option value=\"Jalahalli\">Jalahalli</option>\r\n");
      out.write("                                 <option value=\"Peenya Industry\">Peenya Industry</option>\r\n");
      out.write("                                 <option value=\"Peenya\">Peenya</option>\r\n");
      out.write("                                 <option value=\"Goraguntepalya\">Goraguntepalya</option>\r\n");
      out.write("                                 <option value=\"Yeshwanthpur\">Yeshwanthpur</option>\r\n");
      out.write("                                 <option value=\"Sandal Soap Factory\">Sandal Soap Factory</option>\r\n");
      out.write("                                 <option value=\"Mahalakshmi\">Mahalakshmi</option>\r\n");
      out.write("                                 <option value=\"Rajajinagar\">Rajajinagar</option>\r\n");
      out.write("                                 <option value=\"Kuvempu Road\">Kuvempu Road</option>\r\n");
      out.write("                                 <option value=\"Srirampura\">Srirampura</option>\r\n");
      out.write("                                 <option value=\"Mantri Square Sampige Road\">Mantri Square Sampige Road</option>\r\n");
      out.write("                                 <option value=\"Krantivira Sangolli Rayanna\">Krantivira Sangolli Rayanna (Majestic)</option>\r\n");
      out.write("                                 <option value=\"Chickpete\">Chickpete</option>\r\n");
      out.write("                                 <option value=\"Krishna Rajendra Market\">Krishna Rajendra Market</option>\r\n");
      out.write("                                 <option value=\"National College\">National College</option>\r\n");
      out.write("                                 <option value=\"Lalbagh\">Lalbagh</option>\r\n");
      out.write("                                 <option value=\"South End Circle\">South End Circle</option>\r\n");
      out.write("                                 <option value=\"Jayanagar\">Jayanagar</option>\r\n");
      out.write("                                 <option value=\"Rashtreeya Vidyalaya Road\">Rashtreeya Vidyalaya Road</option>\r\n");
      out.write("                                 <option value=\"Banashankari\">Banashankari</option>\r\n");
      out.write("                                 <option value=\"Jaya Prakash Nagar\">Jaya Prakash Nagar</option>\r\n");
      out.write("                                 <option value=\"Yelachenahalli\">Yelachenahalli</option>\r\n");
      out.write("                                 <option value=\"Anjanapura\">Anjanapura</option>\r\n");
      out.write("                             </select>\r\n");
      out.write("                         </div>\r\n");
      out.write("\r\n");
      out.write("                           <div class=\"mb-3\">\r\n");
      out.write("                 <label for=\"stationNumber\"   style=\"color:white\" class=\"form-label\">Station Number*</label>\r\n");
      out.write("                <input type=\"number\"  name=\"stationNumber\" id=\"stationNumber\" class=\"form-control\" placeholder=\"Enter the stationNumber\">\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                           <div class=\"mb-3\">\r\n");
      out.write("                 <label for=\"trainNumber\"   style=\"color:white\" class=\"form-label\">Train Number*</label>\r\n");
      out.write("                <input type=\"text\"  name=\"trainNumber\" id=\"trainNumber\" class=\"form-control\" placeholder=\"Enter the Train Number\">\r\n");
      out.write("                  </div>\r\n");
      out.write("\r\n");
      out.write("                   <button type=\"submit\" id=\"button\" class=\"btn btn-danger btn-sm rounded-pill\">Add</button>\r\n");
      out.write("           </div>\r\n");
      out.write("            </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </div>\r\n");
      out.write("                                 <div class=\"d-flex justify-content-between align-items-center\" hidden>\r\n");
      out.write("                                 <form action=\"price\" class=\"d-inline\" hidden>\r\n");
      out.write("                                  <input type=\"number\" name=\"price\" class=\"form-control d-inline\" style=\"width: auto;\"hidden >\r\n");
      out.write("                                  <input type=\"submit\" value=\"search By price\" hidden>\r\n");
      out.write("                                </form hidden>\r\n");
      out.write("                                                                  <div class=\"d-flex justify-content-between align-items-center\" hidden>\r\n");
      out.write("                                                                  <form action=\"sourceAndDestination\" class=\"d-inline\" hidden>\r\n");
      out.write("                                                                <input type=\"text\" name=\"source\" class=\"form-control d-inline\" style=\"width: auto;\" hidden>\r\n");
      out.write("                                                                <input type=\"text\" name=\"destination\" class=\"form-control d-inline\" style=\"width: auto;\" hidden>\r\n");
      out.write("                                                               <input type=\"submit\" value=\"search By price\" hidden>\r\n");
      out.write("                                                                      </form>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"fixed-bottom\">\r\n");
      out.write("        <footer class=\"bg-dark text-white py-3\">\r\n");
      out.write("            <div class=\"container text-center\">\r\n");
      out.write("                <p class=\"mb-0\"></p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </footer>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    const destination = () => {\r\n");
      out.write("        let source = document.getElementById(\"sourceId\").value;\r\n");
      out.write("        let destination = document.getElementById(\"destinationId\").value;\r\n");
      out.write("        let button = document.getElementById(\"button\");\r\n");
      out.write("        console.log(\"source: \" + source);\r\n");
      out.write("        console.log(\"destination: \" + destination);\r\n");
      out.write("        if (source === destination) {\r\n");
      out.write("            button.disabled = true;  // Disable the button\r\n");
      out.write("        } else {\r\n");
      out.write("            button.disabled = false;  // Enable the button\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("    document.getElementById(\"sourceId\").addEventListener(\"change\", destination);\r\n");
      out.write("    document.getElementById(\"destinationId\").addEventListener(\"change\", destination);\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js\" integrity=\"sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js\" integrity=\"sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
