/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.38
 * Generated at: 2025-07-25 10:45:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/rajen/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1308849601000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("<head>\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>Metro Official Front Page</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\" crossorigin=\"anonymous\">\r\n");
      out.write("    <script src=\"https://unpkg.com/@nicesapien0/typewriter.js/typewriter.js\"></script>\r\n");
      out.write("        <script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script> <!-- jQuery CDN -->\r\n");
      out.write("        <script src=\"https://cdnjs.cloudflare.com/ajax/libs/typescript/4.0.5/typescript.js\"></script> <!-- TypeScript CDN -->\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <header class=\"bg-dark text-white text-center py-3\">\r\n");
      out.write("        <div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("            <!-- Logo -->\r\n");
      out.write("            <div>\r\n");
      out.write("            <img src=\"https://www.x-workz.in/Logo.png\" alt=\"Coders World Logo\" style=\"max-height: 50px;\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- Heading -->\r\n");
      out.write("                 <h1 class=\"text-center mb-0 flex-grow-1\" ></h1>\r\n");
      out.write("            <nav class=\"mx-0\">\r\n");
      out.write("            <a href=\"MetroRegistration\" class=\"btn btn-primary active btn-sm \">Metro Registration</a>\r\n");
      out.write("              </nav>\r\n");
      out.write("              <br>\r\n");
      out.write("            <nav class=\"mx-2\">\r\n");
      out.write("            <a href=\"userLogin\" class=\"btn btn-primary active btn-sm \">Login</a>\r\n");
      out.write("              </nav>\r\n");
      out.write("\r\n");
      out.write("    </header>\r\n");
      out.write("<h1 style=\"text-align: center; font-size:25px; margin-top: 5px; margin-bottom: 5px;\"><b>ನಮ್ಮ ಮೆಟ್ರೋಗೆ ಸುಸ್ವಾಗತ</b></h1>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("   <div class=\"mt-5 text-center\">\r\n");
      out.write("           <marquee><pre class=\"text-center mb-4 text-success\">The Government of Karnataka announced extensions and routes for the Namma Metro on October 2, 2024. The new corridors will add 59 km of length to the system.</pre></marquee>\r\n");
      out.write("    </div>\r\n");
      out.write("        <div class=\"typewriter-effect\">\r\n");
      out.write("        <div id=\"typewriter-text\" class=\"text\">\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"text-center\">\r\n");
      out.write("       <a href=\"MetroRegistration\" class=\"btn btn-dark btn-sm\">enroll now</a>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"text-center mt-3\">\r\n");
      out.write("    <img src=\"https://english.bmrc.co.in/images/metro/footer-img.png\" alt=\"Descriptive Alt Text\" class=\"img-fluid\">\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <!-- Overlay Card (Black Transparent) -->\r\n");
      out.write("    <div style=\"position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); background-color: rgba(0, 0, 0, 0.7); color: white; padding: 20px; border-radius: 15px; text-align: center; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3);\">\r\n");
      out.write("        <p style=\"font-size: 12px; margin: 0;\">Want to book a ticket?</p>\r\n");
      out.write("                <a href=\"userLogin\" style=\"text-decoration: none; color: white; background-color: rgba(0, 0, 0, 0.5); padding: 15px 30px; border-radius: 8px; font-size: 16px; display: inline-block; margin-top: 15px; width: auto; transition: background-color 0.3s ease-in-out;\">Click Here</a>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("<div style=\"background-color: white; padding: 20px;\">\r\n");
      out.write("    <!-- Main Card Layout -->\r\n");
      out.write("    <div style=\"display: flex; justify-content: space-between; background-color: rgba(0, 0, 0, 0.7); color: white; padding: 20px; border-radius: 10px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.3);\">\r\n");
      out.write("\r\n");
      out.write("        <div style=\"flex: 1; padding: 10px;\">\r\n");
      out.write("            <div style=\"background-color: rgba(0, 0, 0, 0.5); color: white; border-radius: 10px; text-align: center; padding: 20px;\">\r\n");
      out.write("                <h2 class=\"card-title mb-3\"></h2>\r\n");
      out.write("                <img src=\"https://mir-s3-cdn-cf.behance.net/project_modules/disp/fb925221893757.5665bb0ba3c4d.gif\" alt=\"GIF\" style=\"width: 100%; height: auto; border-radius: 10px;\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div style=\"flex: 1; padding: 10px;\">\r\n");
      out.write("            <div style=\"background-color: rgba(0, 0, 0, 0.5); color: white; border-radius: 10px; text-align: center; padding: 20px; display: flex;\">\r\n");
      out.write("                <!-- Third Image on the Left Side of the Second Image -->\r\n");
      out.write("                <div style=\"flex: 1; padding: 10px;\">\r\n");
      out.write("                    <img src=\"https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/681bbd21893757.5665bb0b6bdb3.jpg\" alt=\"Image 1\" style=\"width: 100%; height: auto; border-radius: 10px;\">\r\n");
      out.write("                </div>\r\n");
      out.write("                <div style=\"flex: 1; padding: 10px;\">\r\n");
      out.write("                    <img src=\"https://mir-s3-cdn-cf.behance.net/project_modules/disp/fb925221893757.5665bb0ba3c4d.gif\" alt=\"GIF\" style=\"width: 100%; height: auto; border-radius: 10px;\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div style=\"background-color: rgba(0, 0, 0, 0.5); color: white; border-radius: 10px; text-align: center; padding: 20px; margin-top: 20px;\">\r\n");
      out.write("        <h2 class=\"card-title mb-3\"></h2>\r\n");
      out.write("        <img src=\"https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/6fbd1f21893757.5665bb0b8536b.jpg\" alt=\"Image 2\" style=\"width: 100%; height: auto; border-radius: 10px;\">\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<footer class=\"bg-dark text-white text-center py-3 mt-4\" style=\"position: fixed; bottom: 0; width: 100%; z-index: 999;\">\r\n");
      out.write("    <div class=\"container text-center\">\r\n");
      out.write("        <nav>\r\n");
      out.write("        </nav>\r\n");
      out.write("        <div class=\"left\">\r\n");
      out.write("            <h7 id=\"currentDateTime\"></h7>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("          <script>\r\n");
      out.write("\r\n");
      out.write("          let time=new Date();\r\n");
      out.write("          console.log()\r\n");
      out.write("          document.getElementById(\"currentDateTime\").innerText=time.toLocaleDateString() + \"  \"+time.toLocaleTimeString();\r\n");
      out.write("\r\n");
      out.write("   typewriterConfig = [\"Click here to enroll \", true]\r\n");
      out.write("    typewriter();\r\n");
      out.write("\r\n");
      out.write("          </script>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js\" integrity=\"sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js\" integrity=\"sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
