/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.38
 * Generated at: 2025-07-25 10:50:48 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Information_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>This is Coders World</title>\r\n");
      out.write("    <link rel=\"icon\" type=\"image/x-icon\" href=\"https://www.x-workz.in/Logo.png\"/>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-...\" crossorigin=\"anonymous\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <header class=\"bg-dark text-white text-center py-3\">\r\n");
      out.write("        <div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("            <!-- Logo -->\r\n");
      out.write("            <img src=\"https://www.x-workz.in/Logo.png\" alt=\"Coders World Logo\" style=\"max-height: 50px;\">\r\n");
      out.write("\r\n");
      out.write("            <!-- Heading -->\r\n");
      out.write("       <h1 class=\"text-center mb-0 flex-grow-1\"></h1>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    <br>\r\n");
      out.write("<div style=\"text-align: center;\">\r\n");
      out.write("        <img src=\"https://th.bing.com/th?id=OLC.Kj96CPQlp0+sew480x360&rs=1&pid=ImgDetMain\" alt=\"Descriptive Alt Text\" class=\"img-fluid\" style=\"max-height: 500px; max-width: 500px; display: block; margin: auto;\">\r\n");
      out.write("    </div>\r\n");
      out.write("    <h1><i>Information</i></h1>\r\n");
      out.write("    <p>Bangalore (Namma) Metro is an urban Mass Rapid Transit System (MRTS) with 2 lines and 51 stations serving Bengaluru, Karnatakaâs capital and largest city</p>\r\n");
      out.write("    <p>Construction for Bangalore Metro Phase 1 with 42.30 km of routes started in April 2007. Its first section, connecting Baiyyappanahalli â MG Road on the Purple Line, opened up in 2011. The 6th (and final) section was inaugurated by Indiaâs President on June 17, 2017, and commercial operations started on the next day.</p>\r\n");
      out.write("    <p>Construction work on the 73.921 km Bangalore Metro Phase 2's first new section (Mysore Road  Pattanagere, Reach-2A of Purple Line) started in September 2015. The project faced funding issues due to which a majority of civil construction contracts were awarded only in the first half of 2017.</p>\r\n");
      out.write("    <p>While the Green Lineâs extension to Silk Institute became operational in January 2021, the entire phase, including a 13.9 km underground section of the Pink Line, is expected to be ready no sooner than 2024 after which the metro network will become 116.25 km long.</p>\r\n");
      out.write("    <p>Bangalore Metroâs Phase 3 project with routes totaling 44.65 km is currently pending approval from the Central Governmentâs cabinet. Earlier 105 km of routes were planned. From that, 18 km (Central Silk Board â KR Puram) and 38 km (KR Puram â KIAL Airport) of lines have been expedited and are currently being built in parallel with Phase 2 under Phase 2A and Phase 2B respectively.</p>\r\n");
      out.write("\r\n");
      out.write("    <h2><i>System Specifications</i></h2>\r\n");
      out.write("    <ul>\r\n");
      out.write("        <li>Top Speed: 80 kmph</li>\r\n");
      out.write("        <li>Average Speed: 34 kmph</li>\r\n");
      out.write("        <li>Track Gauge: Standard Gauge â 1435 mm</li>\r\n");
      out.write("        <li>Electrification: 750 V DC Third Rail</li>\r\n");
      out.write("        <li>Signalling: Distance to Go (Purple & Green lines), CBTC (Yellow & Pink lines)</li>\r\n");
      out.write("    </ul>\r\n");
      out.write("\r\n");
      out.write("    <h2><i>Key Figures</i></h2>\r\n");
      out.write("    <ul>\r\n");
      out.write("        <li>Operational: 75.20 km</li>\r\n");
      out.write("        <li>Under Construction: 94.81 km</li>\r\n");
      out.write("        <li>Approved: 44.65 km</li>\r\n");
      out.write("        <li>Proposed: 37 km</li>\r\n");
      out.write("        <li>Daily Ridership: 7.5 lakh/day (October 2023)</li>\r\n");
      out.write("        <li>Rolling Stock: 342 coaches (57 train-sets x 6) supplied by BEML and 216 coaches (36 x 6) to be supplied by CRRC</li>\r\n");
      out.write("    </ul>\r\n");
      out.write("\r\n");
      out.write("    <h2><i>Operational Lines (Phase 1, Phase 2)</i></h2>\r\n");
      out.write("    <ul>\r\n");
      out.write("        <li>Line-1 â Purple Line: Challaghatta â Whitefield (Kadugodi) (42.17 km, 37 stations)</li>\r\n");
      out.write("        <li>Line-2 â Green Line: Madavara â Silk Institute (33.03 km, 32 stations)</li>\r\n");
      out.write("    </ul>\r\n");
      out.write("\r\n");
      out.write("    <h2><i>Under Construction Lines (Phase 2, Phase 2A, Phase 2B)</i></h2>\r\n");
      out.write("    <ul>\r\n");
      out.write("        <li>Line-2 â Green Line: Silk Institute â Anjanapura Depot (0.50 km, 0 stations)</li>\r\n");
      out.write("        <li>Line-3 â Yellow Line: RV Road â Bommasandra (19.143 km, 16 stations)</li>\r\n");
      out.write("        <li>Line-4 â Pink Line: Gottigere (Kalena Agrahara) â Nagawara (21.386 km, 18 stations)</li>\r\n");
      out.write("        <li>Line-5 â Blue Line: Central Silkboard â KR Puram (18.236 km, 13 stations, âORR Lineâ)</li>\r\n");
      out.write("        <li>Line-5 â Blue Line: KR Puram â Hebbal â KIAL Terminals (37 km, 17 stations, âAirport Lineâ)</li>\r\n");
      out.write("    </ul>\r\n");
      out.write("\r\n");
      out.write("    <h2><i>Approved Lines (Phase 3)</i></h2>\r\n");
      out.write("    <ul>\r\n");
      out.write("        <li>Line-6 â Orange Line: Kempapura â JP Nagar 4th Phase (32.15 km, 22 stations)</li>\r\n");
      out.write("        <li>Line-7 â Silver Line: Kadabagare â Hosahalli (12.5 km, 9 stations)</li>\r\n");
      out.write("    </ul>\r\n");
      out.write("\r\n");
      out.write("    <h2><i>Proposed Lines Pending Approvals (Phase 3A)</i></h2>\r\n");
      out.write("    <ul>\r\n");
      out.write("        <li>Line-8 â Red Line: Hebbal â Sarjapur (37 km)</li>\r\n");
      out.write("    </ul>\r\n");
      out.write("\r\n");
      out.write("    <div>\r\n");
      out.write("    <footer class=\"bg-dark text-white text-center py-3 mt-4\" >\r\n");
      out.write("        <div class=\"container text-center\">\r\n");
      out.write("                <p class=\"mb-0\"><a href=\"MetroLogin\" style=\"text-decoration: none\"><h7>Back</h7></a></p>\r\n");
      out.write("                </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
