/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.38
 * Generated at: 2024-12-20 10:49:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ProfileName_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>This is Coders World</title>\r\n");
      out.write("    <link rel=\"icon\" type=\"image/x-icon\" href=\"https://www.x-workz.in/Logo.png\"/>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-...\" crossorigin=\"anonymous\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<title></title>\r\n");
      out.write("<body>\r\n");
      out.write("    <header class=\"bg-dark text-white text-center py-3\">\r\n");
      out.write("        <div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("       <img src=\"https://www.x-workz.in/Logo.png\" alt=\"Coders World Logo\" style=\"max-height: 50px;\">\r\n");
      out.write("       <h1 class=\"text-center mb-0 flex-grow-1\"></h1>\r\n");
      out.write("<div style=\"text-align: center;\">\r\n");
      out.write("    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/getImage/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.imageName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"rounded-circle\" alt=\"img\" width=100/>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("        <div class=\"card mx-auto\" style=\"max-width: 400px;\">\r\n");
      out.write("            <div class=\"card-header\">\r\n");
      out.write("                <h5 class=\"mb-0\"></h5>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"card-body\">\r\n");
      out.write("            <div style=\"text-align: center;\">\r\n");
      out.write("                <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.servletContext.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/getImage/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.imageName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"rounded-circle\" alt=\"img\" width=200/>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("                <form action=\"UpdateUser\" method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("                 <input type=\"text\" name=\"id\" placeholder=\"enter a id\" class=\"form-control form-control-lg\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" hidden>\r\n");
      out.write("                    <div class=\"mb-1\">\r\n");
      out.write("                        <span id=\"fName\" style=\"color:pink; visibility:hidden;\"></span>\r\n");
      out.write("                        <label for=\"firstName\" class=\"form-label\">First Name</label>\r\n");
      out.write("                        <input type=\"text\" name=\"firstName\" id=\"firstName\"\" class=\"form-control\" placeholder=\"Enter your first name\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.firstName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required/>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"mb-1\">\r\n");
      out.write("                          <span id=\"lName\" style=\"color:pink; visibility:hidden;\"></span>\r\n");
      out.write("                        <label for=\"lastName\" class=\"form-label\">Last Name</label>\r\n");
      out.write("                        <input type=\"text\" name=\"lastName\" id=\"lastName\"  class=\"form-control\" placeholder=\"Enter your last name\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.lastName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required/>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"mb-1\">\r\n");
      out.write("                           <span id=\"uName\" style=\"color:pink; visibility:hidden;\" hidden></span>\r\n");
      out.write("                        <label for=\"userName\" class=\"form-label\" hidden>Username</label>\r\n");
      out.write("                        <input type=\"text\" name=\"userName\" id=\"userName\" class=\"form-control\" placeholder=\"Enter your username\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.userName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"hidden/>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"mb-1\">\r\n");
      out.write("                          <span id=\"passwordError\" style=\"color:Red; visibility:hidden;\"></span>\r\n");
      out.write("                        <label for=\"password\" class=\"form-label\" hidden>Password</label>\r\n");
      out.write("                        <input type=\"password\" name=\"password\" id=\"password\"  class=\"form-control\" placeholder=\"Enter your password\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.password}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" hidden/>\r\n");
      out.write("                            <small id=\"passwordHelpInline\" class=\"text-muted\" hidden>\r\n");
      out.write("                              Must be 8-20 characters long.\r\n");
      out.write("                            </small>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"mb-1\">\r\n");
      out.write("                        <label for=\"email\" class=\"form-label\">Email Address</label>\r\n");
      out.write("                        <span id=\"emailError\" style=\"color:blue;\"></span>\r\n");
      out.write("                        <input type=\"email\" name=\"email\" onBlur=\"checkEmail()\" id=\"email\" class=\"form-control\" placeholder=\"name@example.com\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required/>\r\n");
      out.write("                            <small id=\"emailHelp\" class=\"form-text text-muted\">We'll never share your email with anyone else.</small>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"mb-1\">\r\n");
      out.write("                        <span id=\"mobile\" style=\"color:blue; visibility:hidden;\"> </span>\r\n");
      out.write("                        <label for=\"mobileNumber\" class=\"form-label\" >Mobile Number</label>\r\n");
      out.write("                        <input type=\"text\" name=\"mobileNumber\" id=\"mobileNumber\" class=\"form-control\" placeholder=\"Enter your phone number\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.mobileNumber}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"required/>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"mb-1\">\r\n");
      out.write("                        <input type=\"text\" name=\"gender\" id=\"gender\"  class=\"form-control\" placeholder=\"Enter your gender\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.gender}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" hidden>\r\n");
      out.write("                        </div>\r\n");
      out.write("                         <div class=\"mb-1\">\r\n");
      out.write("                         <input type=\"file\" name=\"file\" /><br/>\r\n");
      out.write("                         </div>\r\n");
      out.write("                    <div class=\"mb-1\">\r\n");
      out.write("                    <button type=\"submit\" id=\"button\" class=\"btn btn-dark btn-sm rounded-pill\">Edit</button>\r\n");
      out.write("                    <div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("    <footer class=\"bg-dark text-white py-3\">\r\n");
      out.write("        <div class=\"container text-center\">\r\n");
      out.write("        <p class=\"mb-0\"><a href=\"index\" style=\"text-decoration: none\"><h7>Back</h7></a></p>\r\n");
      out.write("    </footer>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
