/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.38
 * Generated at: 2025-07-25 10:50:04 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class UserSuccessPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Users/rajen/.m2/repository/javax/servlet/jstl/1.2/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1308849601000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    <html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <link rel=\"icon\" type=\"image/x-icon\" href=\"https://www.x-workz.in/Logo.png\"/>\r\n");
      out.write("            <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-...\" crossorigin=\"anonymous\">\r\n");
      out.write("            <link href=\"//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("            <link href=\"https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("            <link href=\"//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("            <link href=\"https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/css/select2.min.css\" rel=\"stylesheet\" />\r\n");
      out.write("            <script src=\"//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\r\n");
      out.write("            <script src=\"//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\"></script>\r\n");
      out.write("            <script src=\"https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.6-rc.0/js/select2.min.js\"></script>\r\n");
      out.write("            <script src=\"https://unpkg.com/axios/dist/axios.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("            <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    </head>\r\n");
      out.write("    <title></title>\r\n");
      out.write("    <body>\r\n");
      out.write("    <header class=\"bg-dark text-white py-3\" style=\"display: flex; justify-content: space-between; align-items: center;\">\r\n");
      out.write("        <div>\r\n");
      out.write("            <img src=\"https://www.x-workz.in/Logo.png\" alt=\"Coders World Logo\" style=\"max-height: 50px;\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"dropdown mb-1\" style=\"margin-left: auto;\">\r\n");
      out.write("            <a class=\"mx-2\" href=\"#\" style=\"color: white; text-decoration: none;\" role=\"button\" id=\"dropdownMenuLink\" data-bs-toggle=\"dropdown\" aria-haspopup=\"true\" aria-expanded=\"false\">\r\n");
      out.write("                Travel Info\r\n");
      out.write("            </a>\r\n");
      out.write("            <div class=\"dropdown-menu\" aria-labelledby=\"dropdownMenuLink\">\r\n");
      out.write("                <a class=\"dropdown-item\" href=\"fareRules\">Tickets</a>\r\n");
      out.write("                <a class=\"dropdown-item\" href=\"LostAndFound\">Lost&Found</a>\r\n");
      out.write("                <a class=\"dropdown-item\" href=\"MetroTimings\">Metro Timings</a>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("                    <nav class=\"mx-3\">\r\n");
      out.write("                    <a href=\"info\"  style=\"color: white; text-decoration: none\">Information</a>\r\n");
      out.write("                    </nav>\r\n");
      out.write("         <nav>\r\n");
      out.write("   <a href=\"abc?userId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${email.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"  style=\"color: white; text-decoration: none\">View Ticket History</a>\r\n");
      out.write("         </nav>\r\n");
      out.write("    </header>\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("<div class=\"image-container\" style=\"position: relative; width: 100%; text-align: center;\">\r\n");
      out.write("    <img src=\"https://en-media.thebetterindia.com/uploads/2017/06/Relax37-1152x603.jpg\" alt=\"Relaxing Image\" style=\"width: 100%; height: auto;\">\r\n");
      out.write("    <!-- Black transparent overlay on top of the image -->\r\n");
      out.write("    <div style=\"position: absolute; top: 0; left: 0; width: 100%; height: 100%; background-color: rgba(0, 0, 0, 0.5); z-index: 1;\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Card positioned above the image -->\r\n");
      out.write("<div class=\"card mx-auto\" style=\"max-width: 800px; position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%); z-index: 2; width: 90%;\">\r\n");
      out.write("    <div class=\"card-body\" style=\"background-color: rgba(255, 255, 255, 0.9); padding: 20px;\">\r\n");
      out.write("        <h4 class=\"card-title\" style=\"text-align: center; font-weight: bold;\"><b>JOURNEY FARE CALCULATOR</b></h4>\r\n");
      out.write("        <form action=\"ticketForm\" id=\"ticketForm\">\r\n");
      out.write("            <div class=\"card mt-4\">\r\n");
      out.write("                <div class=\"card-body bg-white\" style=\"background-color: rgba(255, 255, 255, 0.9);\">\r\n");
      out.write("                    <div class=\"row mb-3\">\r\n");
      out.write("                        <input type=\"email\" id=\"email\" name=\"email\" placeholder=\"user@gmail.com\" id=\"emailId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${email.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" hidden>\r\n");
      out.write("                        <input type=\"number\" id=\"id\" name=\"id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${email.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" hidden>\r\n");
      out.write("                        <div class=\"col-md-4\">\r\n");
      out.write("                            <label for=\"source\" class=\"form-label\">From:</label>\r\n");
      out.write("                            <select class=\"form-select form-control select2\" id=\"sourceBox\" onchange=\"updatePrice()\" name=\"source\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${source}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" aria-label=\"Source selection\">\r\n");
      out.write("                                <option selected>Select Source:</option>\r\n");
      out.write("                                ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                            </select>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-md-4\">\r\n");
      out.write("                            <label for=\"destination\" class=\"form-label\">To:</label>\r\n");
      out.write("                            <select class=\"form-select form-control select2\" onchange=\"checkPrice()\" id=\"selectBox\" name=\"destination\" aria-label=\"Destination selection\">\r\n");
      out.write("                                <option selected>Select Destination:</option>\r\n");
      out.write("                                ");
      if (_jspx_meth_c_005fforEach_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                            </select>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"col-md-4\" id=\"priceResult\">\r\n");
      out.write("                            <label for=\"price\" name=\"labelPrice\" id=\"labelPriceId\" class=\"form-label\">Price:</label>\r\n");
      out.write("                            <input type=\"number\" name=\"price\" id=\"priceId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${price.price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"form-control form-control-sm\" readonly>\r\n");
      out.write("                            <p id=\"priceText\"></p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-md-8\">\r\n");
      out.write("                        <button type=\"submit\" id=\"submitBtn\" class=\"btn btn-danger active btn-sm form-control form-control-sm\" style=\"background-color: purple; color: white;\">Book a Ticket</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("                                    <pre style=\"text-align:center; color:green;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${booked}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</pre>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("    <h5 style=\"text-align:center; color:green;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h5>\r\n");
      out.write("    <div class=\"container mt-5\">\r\n");
      out.write("    <h3 style=\"font-family: Arial, sans-serif; color: black; text-align: center; text-transform: uppercase; letter-spacing: 2px;\">\r\n");
      out.write("        Benefits Of Contactless Smart Cards\r\n");
      out.write("    </h3>\r\n");
      out.write("<div class=\"container mt-5\">\r\n");
      out.write("    <div class=\"row\">\r\n");
      out.write("        <!-- First Image and Information about Smart Cards -->\r\n");
      out.write("        <div class=\"col-md-4 d-flex flex-column align-items-start\">\r\n");
      out.write("        <h8 style=\"font-family: Arial, sans-serif; color: green;\">->Smart cards will be used to carry multiple trips</h8>\r\n");
      out.write("            <img src=\"https://english.bmrc.co.in/images/metro/tickets/tickets-logo.jpg\" alt=\"Descriptive Alt Text\" class=\"img-fluid\" style=\"height: 200px;\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"col-md-4 d-flex flex-column align-items-center\">\r\n");
      out.write("        <h8 style=\"font-family: Arial, sans-serif; color: green;\">->Tokens</h8>\r\n");
      out.write("            <img src=\"https://english.bmrc.co.in/images/metro/tickets/coin.jpg\" alt=\"Descriptive Alt Text\" class=\"img-fluid\" style=\"max-height: 200px;\">\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <!-- Third Image about Smart Card -->\r\n");
      out.write("        <div class=\"col-md-4 d-flex flex-column align-items-end\">\r\n");
      out.write("        <a href=\"smartCards\" style=\"font-family: Arial, sans-serif; color: green;\">->Smart cards</a>\r\n");
      out.write("            <img src=\"https://english.bmrc.co.in/images/metro/tickets/smartcard.jpg\" alt=\"Descriptive Alt Text\" class=\"img-fluid\" style=\"max-height: 200px;\">\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Outer Card to hold the \"Stored Value Ticket\" Text -->\r\n");
      out.write("<div class=\"card mt-5\">\r\n");
      out.write("    <div class=\"card-body\">\r\n");
      out.write("        <!-- Inner Card for \"Stored Value Ticket\" Information -->\r\n");
      out.write("        <div class=\"card\">\r\n");
      out.write("            <div class=\"card-body bg-light\">\r\n");
      out.write("                <h4 class=\"card-title\"><b>Stored Value Ticket (Varshik)</b></h4>\r\n");
      out.write("                <p><b>Smart cards will be used to carry multiple trips.</b></p>\r\n");
      out.write("                <p>The User can load an amount in multiples of Rs.50/- upto a maximum of Rs 3000/- into the Smart Card.</p>\r\n");
      out.write("                <p>The stored value in the ticket will be reduced to the range of managed trips.</p>\r\n");
      out.write("                <p>Get 5% discount for smart cards, over token fare.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"card mt-5\">\r\n");
      out.write("    <div class=\"card-body\">\r\n");
      out.write("        <!-- Inner Card for QR Based Ticketing Information -->\r\n");
      out.write("        <div class=\"card\">\r\n");
      out.write("            <div class=\"card-body bg-light\">\r\n");
      out.write("                <h4 class=\"card-title\"><b>BMRCL QR Based Ticketing System</b></h4>\r\n");
      out.write("                <p><b>BMRCL has launched QR based ticketing through Namma Metro App and WhatsApp instant messaging. BMRCL is the first Metro in the Global Transit space to introduce end-to-end ticketing system on WhatsApp.</b></p>\r\n");
      out.write("                <p>With this facility, commuters can purchase their travel ticket on their smartphone. The instant messaging service on WhatsApp shall also include a Chatbot service, and commuters can reach this chatbot through WhatsApp number 81055-56677. This facility is available in both English and Kannada. For more details, please see: <a href=\"https://youtu.be/dr66mPsgR3Y\" target=\"_blank\">YouTube Video</a></p>\r\n");
      out.write("                <h5><b>Purchasing Tickets:</b></h5>\r\n");
      out.write("                <p>The commuters can select their desired station of entry and exit on the Namma Metro App or WhatsApp Chatbot. After selecting stations, the fare for the travel is automatically calculated. The commuter can make the payment through their desired digital mode. After the successful payment, the QR ticket is generated on the platform (Namma Metro App or WhatsApp) as chosen by the commuter.</p>\r\n");
      out.write("                <h5><b>Gaining Entry and Exit:</b></h5>\r\n");
      out.write("                <p>Entry to the station shall be done through the QR ticket generated, and after the completion of the journey, the commuter can present the same QR ticket to the designated slot for QR ticket reading on the AFC gate.</p>\r\n");
      out.write("                <h5><b>Validity of the QR Ticket:</b></h5>\r\n");
      out.write("                <p>One QR ticket may be brought at a time, and it is valid for one day. The passenger may enter anytime during the day after purchasing a QR ticket.</p>\r\n");
      out.write("                <h5><b>Refund Policy:</b></h5>\r\n");
      out.write("                <p>The passenger may cancel the QR ticket before entering, if they desire a refund. For cancelled QR tickets, the money will be transferred back to the source account within seven days. In the event that the passenger has entered the AFC gate, no refund will be given. If the QR ticket is not cancelled within a day, no refund will be provided.</p>\r\n");
      out.write("                <p><b>Metro QR Code Tickets are also available on Paytm and Yatra App.</b></p>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("    <footer class=\"bg-dark text-white text-center py-3 mt-4\">\r\n");
      out.write("        <div class=\"container text-center\">\r\n");
      out.write("            <p class=\"mb-0\">\r\n");
      out.write("                <a href=\"userCanLoginHere\" style=\"text-decoration: none; color: white;\">\r\n");
      out.write("                    Back\r\n");
      out.write("                </a>\r\n");
      out.write("            </p>\r\n");
      out.write("        </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("\r\n");
      out.write("    <script type=\"text/javascript\">\r\n");
      out.write("      $('.select2').select2();\r\n");
      out.write("\r\n");
      out.write("     function checkUserId(){\r\n");
      out.write("     var userId =  document.getElementById(\"userId\").value;\r\n");
      out.write("     console.log(userId)\r\n");
      out.write("     }\r\n");
      out.write("     function updatePrice()\r\n");
      out.write("         {\r\n");
      out.write("         var select = document.getElementById(\"sourceBox\");\r\n");
      out.write("        alert(select.options[select.selectedIndex].value);\r\n");
      out.write("         }\r\n");
      out.write("        function destination() {\r\n");
      out.write("        var select = document.getElementById(\"selectBox\");\r\n");
      out.write("        alert(select.options[select.selectedIndex].value);\r\n");
      out.write("    }\r\n");
      out.write("        const checkPrice = async () => {\r\n");
      out.write("        const source = document.getElementById(\"sourceBox\").value;\r\n");
      out.write("        const destination = document.getElementById(\"selectBox\").value;\r\n");
      out.write("        const email = document.getElementById(\"email\").value;\r\n");
      out.write("        const id=    document.getElementById(\"id\").value;\r\n");
      out.write("        console.log(\"Source selected:\", source);\r\n");
      out.write("        console.log(\"Destination selected:\", destination)\r\n");
      out.write("        try {\r\n");
      out.write("            const response = await axios.get(`http://localhost:8080/metro-application/sourceAndDestination`, {\r\n");
      out.write("                params: {\r\n");
      out.write("                    source: source,\r\n");
      out.write("                    destination: destination,\r\n");
      out.write("                    email:email,\r\n");
      out.write("                    id:id\r\n");
      out.write("                }\r\n");
      out.write("            });\r\n");
      out.write("            console.log(\"Response from server:\", response.data);\r\n");
      out.write("            const price = response.data;\r\n");
      out.write("            if (price===response.data) {\r\n");
      out.write("                document.getElementById(\"priceId\").value = price;\r\n");
      out.write("                document.getElementById(\"priceText\").innerText =\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${price}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("            } else {\r\n");
      out.write("                document.getElementById(\"priceId\").value = \"\";\r\n");
      out.write("                document.getElementById(\"priceText\").innerText = \"Price not found.\";\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("        } catch (error) {\r\n");
      out.write("            console.error(\"Error fetching price:\", error);\r\n");
      out.write("        }\r\n");
      out.write("    };\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js\" integrity=\"sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("        <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js\" integrity=\"sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("        </body>\r\n");
      out.write("    </html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f0_reused = false;
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /UserSuccessPage.jsp(65,32) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("source");
      // /UserSuccessPage.jsp(65,32) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems(new org.apache.jasper.el.JspValueExpression("/UserSuccessPage.jsp(65,32) '${uniqueSources}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${uniqueSources}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                                    <option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${source}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${source}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            out.write("                                ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
      _jspx_th_c_005fforEach_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f1 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    boolean _jspx_th_c_005fforEach_005f1_reused = false;
    try {
      _jspx_th_c_005fforEach_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f1.setParent(null);
      // /UserSuccessPage.jsp(75,32) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setVar("destination");
      // /UserSuccessPage.jsp(75,32) name = items type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f1.setItems(new org.apache.jasper.el.JspValueExpression("/UserSuccessPage.jsp(75,32) '${uniqueDestinations}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${uniqueDestinations}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int[] _jspx_push_body_count_c_005fforEach_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f1 = _jspx_th_c_005fforEach_005f1.doStartTag();
        if (_jspx_eval_c_005fforEach_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("                                    <option value=\"");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${destination}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write('"');
            out.write('>');
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${destination}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</option>\r\n");
            out.write("                                ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f1);
      _jspx_th_c_005fforEach_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fforEach_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fforEach_005f1_reused);
    }
    return false;
  }
}
