/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.38
 * Generated at: 2025-07-25 10:46:29 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class UserRegistration_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title></title>\r\n");
      out.write("    <link rel=\"icon\" type=\"image/x-icon\" href=\"https://www.x-workz.in/Logo.png\"/>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\" crossorigin=\"anonymous\"/>\r\n");
      out.write("    <script src=\"https://unpkg.com/axios/dist/axios.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/sweetalert2@11\"></script>\r\n");
      out.write("    <script src=\"https://unpkg.com/@nicesapien0/typewriter.js/typewriter.js\"></script>\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css\">\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <header class=\"bg-dark text-white text-center py-3\">\r\n");
      out.write("        <div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("            <!-- Logo -->\r\n");
      out.write("            <img src=\"https://www.x-workz.in/Logo.png\" alt=\"Coders World Logo\" class=\"img-fluid\" style=\"max-height: 50px;\">\r\n");
      out.write("            <h1 class=\"text-center mb-0 flex-grow-1\"></h1>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    <div class=\"container mt-5\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <!-- Image Column on the Left (Mobile Responsiveness) -->\r\n");
      out.write("            <div class=\"col-12 col-md-6 d-flex flex-column justify-content-start align-items-center\" style=\"height: 100vh;\">\r\n");
      out.write("                <img src=\"https://webtopup.bmrc.co.in/contents/images/bmrc-card-front.png\" alt=\"Descriptive Alt Text\" class=\"img-fluid\" style=\"max-height: 400px;\"/>\r\n");
      out.write("                <h3 style=\"margin-top: 20px; text-align: center;\" id=\"typewriterText\">\r\n");
      out.write("                    <i>Save Money, Save Time Use</i> <b><u>BMRC</u></b> Smart Card\r\n");
      out.write("                </h3>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <div class=\"col-12 col-md-6\">\r\n");
      out.write("                <div class=\"card mx-auto\" style=\"max-width: 100%;\">\r\n");
      out.write("                    <div class=\"card-header\">\r\n");
      out.write("                        <h5 class=\"mb-0\">Register Here</h5>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"card-body bg-light\">\r\n");
      out.write("                        <h5>Create New Account</h5>\r\n");
      out.write("                        <form action=\"userRegistration\" method=\"post\" onSubmit=\"return validate(event)\">\r\n");
      out.write("                        <div class=\"mb-3\">\r\n");
      out.write("                            <label id=\"firstNameLabelId\" for=\"firstName\">\r\n");
      out.write("                                First Name :\r\n");
      out.write("                                <svg xmlns=\"http://www.w3.org/2000/svg\" width=\"15\" height=\"13\" fill=\"currentColor\" class=\"bi bi-person-circle\" viewBox=\"0 0 16 16\">\r\n");
      out.write("                                  <path d=\"M11 6a3 3 0 1 1-6 0 3 3 0 0 1 6 0\"/>\r\n");
      out.write("                                  <path fill-rule=\"evenodd\" d=\"M0 8a8 8 0 1 1 16 0A8 8 0 0 1 0 8m8-7a7 7 0 0 0-5.468 11.37C3.242 11.226 4.805 10 8 10s4.757 1.225 5.468 2.37A7 7 0 0 0 8 1\"/>\r\n");
      out.write("                                </svg>\r\n");
      out.write("                            </label>\r\n");
      out.write("                            <input type=\"text\" id=\"firstId\" name=\"firstName\" onBlur=\"checkFirstName()\" class=\"form-control\" placeholder=\"Enter only alphabets and spaces\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.firstName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required/>\r\n");
      out.write("                        </div>\r\n");
      out.write("\r\n");
      out.write("                            <div class=\"mb-3\">\r\n");
      out.write("                                <label id=\"lastNameLabelId\" for=\"lastName\">Last Name :</label>\r\n");
      out.write("                                <input type=\"text\" id=\"lastId\" name=\"lastName\" onBlur=\"checkLastName()\" class=\"form-control\" placeholder=\"Enter Your last Name\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.lastName}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required/>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"mb-3\">\r\n");
      out.write("                                <label id=\"dateLabelId\">DateOfBirth :</label>\r\n");
      out.write("                                <input type=\"date\" name=\"dateOfBirth\" onBlur=\"checkDateOfBirth()\" id=\"dateId\" class=\"form-control\" placeholder=\"Enter Your Date of Birth\" required/>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"mb-3\">\r\n");
      out.write("                                <label id=\"emailLabelId\" for=\"email\">Email Address :</label>\r\n");
      out.write("                                <input type=\"email\" id=\"emailId\" name=\"email\" onBlur=\"checkEmail()\" class=\"form-control\" placeholder=\"Enter valid Email address\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required/>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"mb-3\">\r\n");
      out.write("                                <label id=\"mobileLabelId\" for=\"mobile\">Mobile No :</label>\r\n");
      out.write("                                <input type=\"text\" id=\"mobileId\" name=\"mobileNumber\" class=\"form-control\" onBlur=\"checkMobileNumber()\" placeholder=\"Enter 10 digit valid mobile number\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.mobileNumber}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required/>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"mb-3\">\r\n");
      out.write("                                <label id=\"labelId\" for=\"password\">Password :</label>\r\n");
      out.write("                                <input type=\"text\" id=\"passId\" name=\"password\" onBlur=\"checkPassword()\" class=\"form-control\" placeholder=\"Enter Your password\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.password}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required/>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"mb-3\">\r\n");
      out.write("                                <label id=\"labelConfirmId\" for=\"ConfirmPassword\">ReType Password:</label>\r\n");
      out.write("                                <input type=\"text\" id=\"confirmPasswordId\" onBlur=\"checkConfirm()\" class=\"form-control\" name=\"confirmPassword\" placeholder=\"Enter Your Confirm password\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.confirmPassword}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required/>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <div class=\"col-md-6 mb-1\">\r\n");
      out.write("                                <label class=\"form-label\">Gender :</label>\r\n");
      out.write("                                <div>\r\n");
      out.write("                                    <input type=\"radio\" id=\"male\" name=\"gender\" value=\"male\">\r\n");
      out.write("                                    <label for=\"male\">Male</label>\r\n");
      out.write("                                    <input type=\"radio\" id=\"female\" name=\"gender\" value=\"female\">\r\n");
      out.write("                                    <label for=\"female\">Female</label>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                            <button type=\"submit\" class=\"btn btn-dark btn-sm rounded-pill\" style=\"background-color: purple; color: white;\" onclick=\"checkGender()\" id=\"btnId\">Register</button>\r\n");
      out.write("                            <p class=\"mandatory-text\">* Mandatory Fields</p>\r\n");
      out.write("                            <p class=\"terms-text\"><i>Please read below Terms and Conditions</i></p>\r\n");
      out.write("                            <ul style=\"color: black; margin-top: 20px; font-size: 14px;\">\r\n");
      out.write("                                <li>Smart Card Engraved Id that you want to register should be correct. BMRC will not be liable if you enter incorrect Engraved Id.</li>\r\n");
      out.write("                                <li>Your metro card balance can be updated immediately after successful recharge at Card Top-Up Terminals (CTTs) installed at all metro stations.</li>\r\n");
      out.write("                                <li>You can update the balance of your metro card at Card Top-Up Terminals (CTTs) till 15 days from the date of recharge.</li>\r\n");
      out.write("                                <li>Also, your metro card balance will be automatically updated on the AFC entry gate (during tapping of your card at AFC entry gates) at any Bangalore Metro station after 1 hour and before 7 days from the time of successful recharge.</li>\r\n");
      out.write("                                <li>If the smart card is not presented at CTT or Automatic gate for card balance update within 15 days from the date of recharge, the amount will be refunded automatically after deducting a service fee of 2.5% within 30 days.</li>\r\n");
      out.write("                            </ul>\r\n");
      out.write("                        </form>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"modal fade\" id=\"successModal\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"successModalLabel\" aria-hidden=\"true\">\r\n");
      out.write("        <div class=\"modal-dialog\" role=\"document\">\r\n");
      out.write("            <div class=\"modal-content\">\r\n");
      out.write("                <div class=\"modal-header\">\r\n");
      out.write("                    <h5 class=\"modal-title\" id=\"successModalLabel\">Registration Success</h5>\r\n");
      out.write("                    <button type=\"button\" class=\"close\" data-dismiss=\"modal\" aria-label=\"Close\">\r\n");
      out.write("                        <span aria-hidden=\"true\">&times;</span>\r\n");
      out.write("                    </button>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-body\">\r\n");
      out.write("                    Registration completed successfully! Welcome aboard.\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"modal-footer\">\r\n");
      out.write("                    <button type=\"button\" class=\"btn btn-secondary\" data-dismiss=\"modal\">Close</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"fixed-bottom\">\r\n");
      out.write("        <footer class=\"bg-dark text-white text-center py-3 mt-4\">\r\n");
      out.write("        <p class=\"mb-0\"><a href=\"MetroRegistration\" style=\"text-decoration: none; color: white;\"><h7>Back</h7></a></p>\r\n");
      out.write("        </footer>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("    const button = document.getElementById(\"btnId\");\r\n");
      out.write("\r\n");
      out.write("const checkFirstName = () => {\r\n");
      out.write("    var regex = /^[A-Za-z\\s]+$/;\r\n");
      out.write("    let firstName = document.getElementById(\"firstId\").value;\r\n");
      out.write("    const button = document.getElementById(\"btnId\");\r\n");
      out.write("    const label = document.getElementById(\"firstNameLabelId\");\r\n");
      out.write("\r\n");
      out.write("    if (firstName.length > 3 && firstName.length <= 20 && firstName.trim() !== '' && regex.test(firstName)) {\r\n");
      out.write("        console.log(\"valid first name\");\r\n");
      out.write("        label.innerHTML = \"First Name:\";\r\n");
      out.write("         document.getElementById(\"firstId\").style.border = \"none\";\r\n");
      out.write("        button.disabled = false;\r\n");
      out.write("    } else {\r\n");
      out.write("        console.log(\"Invalid first name\");\r\n");
      out.write("        label.innerHTML = \"<pre>Invalid</pre>\";\r\n");
      out.write("         label.style.color = \"\";\r\n");
      out.write("         label.innerHTML = \"First Name:\";\r\n");
      out.write("        document.getElementById(\"firstId\").style.border = \"solid 1px red\";\r\n");
      out.write("        button.disabled = true;\r\n");
      out.write("    }\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("document.getElementById(\"firstId\").addEventListener(\"input\", checkFirstName);\r\n");
      out.write("\r\n");
      out.write("    const checkLastName = () => {\r\n");
      out.write("        var regex = /^[A-Za-z\\s]+$/;\r\n");
      out.write("        let lastName = document.getElementById(\"lastId\").value;\r\n");
      out.write("         let labelId = document.getElementById(\"labelId\").value;\r\n");
      out.write("        const button = document.getElementById(\"btnId\");\r\n");
      out.write("        if (lastName.length>0 && lastName.trim() !== '') {\r\n");
      out.write("        document.getElementById(\"lastlId\").style.border = \"none\";\r\n");
      out.write("            button.disabled = false;\r\n");
      out.write("        } else {\r\n");
      out.write("            document.getElementById(\"lastId\").style.border = \"solid 1px red\";\r\n");
      out.write("            document.getElementById(\"lastNameLabelId\").style.visibility = \"visible\";\r\n");
      out.write("            document.getElementById(\"lastNameLabelId\").style.color = \"Black\";\r\n");
      out.write("            button.disabled = true;\r\n");
      out.write("        }\r\n");
      out.write("    };\r\n");
      out.write("\r\n");
      out.write("    const checkEmail = async () => {\r\n");
      out.write("        let emailId = document.getElementById(\"emailId\").value;\r\n");
      out.write("         const button = document.getElementById(\"btnId\");\r\n");
      out.write("        const response = await axios(\"http://localhost:8080/metro-application/FindEmail?email=\" + emailId);\r\n");
      out.write("        if (response.data === \"email user already existed\") {\r\n");
      out.write("            document.getElementById(\"emailLabelId\").innerText = response.data;\r\n");
      out.write("            button.disabled = true;\r\n");
      out.write("        } else if (emailId.length < 5 || !/\\S+@\\S+\\.\\S+/.test(emailId)) {\r\n");
      out.write("            document.getElementById(\"emailLabelId\").innerHTML = \"<i>Please enter a valid email</i>\";\r\n");
      out.write("            document.getElementById(\"emailLabelId\").style.color = \"red\";\r\n");
      out.write("            button.disabled = true;\r\n");
      out.write("        } else {\r\n");
      out.write("            document.getElementById(\"emailLabelId\").innerText = \"\";\r\n");
      out.write("            console.log(\"valid email\");\r\n");
      out.write("            button.disabled = false;\r\n");
      out.write("        }\r\n");
      out.write("    };\r\n");
      out.write("\r\n");
      out.write("    const checkPassword = () => {\r\n");
      out.write("        let password = document.getElementById(\"passId\").value;\r\n");
      out.write("         const button = document.getElementById(\"btnId\");\r\n");
      out.write("        if (password.length > 5) {\r\n");
      out.write("            console.log(\"valid password\");\r\n");
      out.write("            button.disabled = false;\r\n");
      out.write("        } else {\r\n");
      out.write("            document.getElementById(\"passId\").style.border = \"solid 1px red\";\r\n");
      out.write("            document.getElementById(\"passId\").style.color = \"red\";\r\n");
      out.write("            button.disabled = true;\r\n");
      out.write("            console.log(\"Invalid password\");\r\n");
      out.write("        }\r\n");
      out.write("    };\r\n");
      out.write("\r\n");
      out.write("    const checkMobileNumber = () => {\r\n");
      out.write("        let mobileNumber = document.getElementById(\"mobileId\").value;\r\n");
      out.write("         const button = document.getElementById(\"btnId\");\r\n");
      out.write("        if (mobileNumber.length === 10) {\r\n");
      out.write("            console.log(\"valid mobile number\");\r\n");
      out.write("            button.disabled = false;\r\n");
      out.write("        } else {\r\n");
      out.write("            document.getElementById(\"mobileId\").style.border = \"solid 1px red\";\r\n");
      out.write("            document.getElementById(\"mobileId\").style.color = \"red\";\r\n");
      out.write("            button.disabled = true;\r\n");
      out.write("            console.log(\"invalid mobile number\");\r\n");
      out.write("        }\r\n");
      out.write("    };\r\n");
      out.write("\r\n");
      out.write("    const checkGender = () => {\r\n");
      out.write("        let male = document.getElementById(\"male\");\r\n");
      out.write("        let female = document.getElementById(\"female\");\r\n");
      out.write("        const button = document.getElementById(\"btnId\");\r\n");
      out.write("        if (male.checked || female.checked) {\r\n");
      out.write("            button.disabled = false;\r\n");
      out.write("        } else {\r\n");
      out.write("            button.disabled = true;\r\n");
      out.write("            alert(\"Please select gender.\");\r\n");
      out.write("        }\r\n");
      out.write("    };\r\n");
      out.write("\r\n");
      out.write("const checkConfirm = () => {\r\n");
      out.write("    const password = document.getElementById(\"passId\").value;\r\n");
      out.write("    const confirmPassword = document.getElementById(\"confirmPasswordId\").value;\r\n");
      out.write("    const button = document.getElementById(\"btnId\");\r\n");
      out.write("\r\n");
      out.write("    if (password === confirmPassword && password !== \"\") {\r\n");
      out.write("        button.disabled = false;\r\n");
      out.write("        document.getElementById(\"confirmPasswordId\").style.border = \"\";\r\n");
      out.write("        document.getElementById(\"confirmPasswordId\").style.color = \"\";\r\n");
      out.write("    } else {\r\n");
      out.write("        button.disabled = true;\r\n");
      out.write("        document.getElementById(\"confirmPasswordId\").style.border = \"solid 1px red\";\r\n");
      out.write("        document.getElementById(\"confirmPasswordId\").style.color = \"red\";\r\n");
      out.write("        if (password === \"\" && confirmPassword === \"\") {\r\n");
      out.write("            alert(\"Password and Confirm Password do not match.\");\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("};\r\n");
      out.write("\r\n");
      out.write("    const checkDateOfBirth = () => {\r\n");
      out.write("        let dateOfBirth = document.getElementById(\"dateId\").value;\r\n");
      out.write("        let today = new Date().toISOString().split('T')[0];\r\n");
      out.write("            const button = document.getElementById(\"btnId\");\r\n");
      out.write("        if (dateOfBirth === today) {\r\n");
      out.write("            document.getElementById(\"dateLabelId\").innerHTML = \"<pre>Not a valid date</pre>\";\r\n");
      out.write("            document.getElementById(\"dateId\").style.border = \"solid 1px red\";\r\n");
      out.write("            document.getElementById(\"dateLabelId\").style.color = \"red\";\r\n");
      out.write("            button.disabled = true;\r\n");
      out.write("        } else {\r\n");
      out.write("            document.getElementById(\"dateLabelId\").innerText = \"\";\r\n");
      out.write("            document.getElementById(\"dateId\").style.border = \"solid 1px green\";\r\n");
      out.write("            button.disabled = false;\r\n");
      out.write("        }\r\n");
      out.write("    };\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
