/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.38
 * Generated at: 2025-07-25 10:49:14 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class UserEmail_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title></title>\r\n");
      out.write("        <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css\" rel=\"stylesheet\" integrity=\"sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC\" crossorigin=\"anonymous\">\r\n");
      out.write("        <script src=\"https://unpkg.com/axios/dist/axios.min.js\"></script>\r\n");
      out.write("            <script src=\"https://code.jquery.com/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("            <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("</body>\r\n");
      out.write("    <header class=\"bg-dark text-white text-center py-3\">\r\n");
      out.write("        <div class=\"d-flex justify-content-between align-items-center\">\r\n");
      out.write("            <!-- Logo -->\r\n");
      out.write("            <img src=\"https://www.x-workz.in/Logo.png\" alt=\"Coders World Logo\" style=\"max-height: 50px;\">\r\n");
      out.write("\r\n");
      out.write("            <!-- Heading -->\r\n");
      out.write("       <h1 class=\"text-center mb-0 flex-grow-1\"></h1>\r\n");
      out.write("        </div>\r\n");
      out.write("    </header>\r\n");
      out.write("<h3 style=\"font-family: 'Arial', sans-serif; text-align: center; margin-right: -237px; margin-top: 35px; font-size: 20px; color: black; letter-spacing: 2px; text-transform: uppercase;\">My Account</h3>\r\n");
      out.write("<div class=\"container mt-5\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <!-- Image Column on the Left -->\r\n");
      out.write("            <div class=\"col-md-6 d-flex justify-content-center align-items-center\">\r\n");
      out.write("    <div id=\"carouselExampleSlidesOnly\" class=\"carousel\" data-bs-ride=\"carousel\">\r\n");
      out.write("        <div class=\"carousel-inner\">\r\n");
      out.write("            <div class=\"carousel-item active\">\r\n");
      out.write("            <img src=\"https://www.tripsavvy.com/thmb/n2oAmjOEl-P3r8VXiuv2hu9bqZc=/960x0/filters:no_upscale():max_bytes(150000):strip_icc()/GettyImages-1081803176-fd11b444454a416ca43a88be77eaeed6.jpg\" class=\"d-flex justify-content-between align-items-center\" style=\"max-height: 300px; max-width:4000px\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"carousel-item\">\r\n");
      out.write("                <img src=\"https://english.bmrc.co.in/images/metro/banner1.jpg\"  style=\"max-height: 300px;\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"carousel-item \">\r\n");
      out.write("                <img src=\"https://english.bmrc.co.in/images/metro/homepage/about-us.jpg\"  style=\"max-height: 300px;\">\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"card mx-5\" style=\"max-width: 500px;\">\r\n");
      out.write("    <div class=\"card-body bg-light\">\r\n");
      out.write("        <form action=\"User\"  class=\"row g-3\">\r\n");
      out.write("        <b>Login:</b>\r\n");
      out.write("            <div class=\"mb-1\">\r\n");
      out.write("                <span for=\"emailId\" id=\"emailLabelId\"class=\"form-label\" >User Email*</span>\r\n");
      out.write("                    <input type=\"email\"  id=\"emailId\"  onblur=\"checkEmail()\" name=\"email\" placeholder=\"User@gmail.com\" id=\"emailId\" class=\"form-control\"  value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${email.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"required>\r\n");
      out.write("            </div>\r\n");
      out.write("                    <div class=\"col-auto\">\r\n");
      out.write("                     <button type=\"submit\" name=\"button\" class=\"btn btn-primary btn-sm rounded-sm border border-light rounded-pill\">Get OTP</button>\r\n");
      out.write("                     </div>\r\n");
      out.write("                    <br>\r\n");
      out.write("                    </form>\r\n");
      out.write("\r\n");
      out.write("                 <form action=\"loginHere\">\r\n");
      out.write("                <input type=\"email\" id=\"email\" name=\"email\" placeholder=\"User@gmail.com\" id=\"email\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${email.email}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" hidden>\r\n");
      out.write("                <input type=\"number\" id=\"id\" name=\"id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${email.id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" hidden>\r\n");
      out.write("               <div class=\"mb-3\">\r\n");
      out.write("               <input type=\"text\" placeholder=\"Enter OTP\" name=\"otp\" class=\"form-control\"> <h7 class=\"text-center\" style=\"color:red\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${emailError}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h7>\r\n");
      out.write("               </div>\r\n");
      out.write("               <div class=\"mb-3\">\r\n");
      out.write("             <button type=\"submit\"  id=\"button\" class=\"btn btn-dark btn-sm rounded-pill\">Submit</button>\r\n");
      out.write("              </div>\r\n");
      out.write("             </form>\r\n");
      out.write("            </div>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("<h5 style=\"text-align:center; color:red;\" >");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${message}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h5>\r\n");
      out.write("\r\n");
      out.write("    <div class=\"fixed-bottom\">\r\n");
      out.write("    <footer class=\"bg-dark text-white text-center py-3 mt-4\" >\r\n");
      out.write("        <div class=\"container text-center\">\r\n");
      out.write("                <p class=\"mb-0\"><a href=\"userLogin\" style=\"text-decoration: none; color: white;\"><h7>Back</h7></a></p>\r\n");
      out.write("                </div>\r\n");
      out.write("    </footer>\r\n");
      out.write("</div>\r\n");
      out.write("           <script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("        $(document).ready(function(){\r\n");
      out.write("            setInterval(()=> {\r\n");
      out.write("                $(\".carousel\").carousel('next');\r\n");
      out.write("            }, 1000);\r\n");
      out.write("    });\r\n");
      out.write("\r\n");
      out.write("const checkEmail = async () => {\r\n");
      out.write("    const email = document.getElementById(\"emailId\").value;\r\n");
      out.write("    const label = document.getElementById(\"emailLabelId\");\r\n");
      out.write("        var button =        document.getElementById(\"button\");\r\n");
      out.write("    const response = await axios.get(\"http://localhost:8080/metro-application/FindEmail\", { params: { email: email } });\r\n");
      out.write("    console.log(response.data);\r\n");
      out.write("    if (response.data === \"email user already existed\") {\r\n");
      out.write("        label.innerText = response.data;\r\n");
      out.write("        label.style.color=\"red\";\r\n");
      out.write("    } else {\r\n");
      out.write("        label.innerText = \"Please enter valid email\";\r\n");
      out.write("        label.style.color = \"red\";\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("    <script src=\"https://code.jquery.com/jquery-3.5.1.slim.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js\"></script>\r\n");
      out.write("    <script src=\"https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
